// Generated by CoffeeScript 1.6.3
(function() {
  ({
    "name": "webapp-0",
    "version": "0.0.0",
    "dependencies": {},
    "devDependencies": {
      "ejs": "*"
    },
    "engines": {
      "node": ">=0.8.0"
    }
  });

}).call(this);
