// Generated by CoffeeScript 1.6.3
(function() {
  var Model, User, jQuery;

  jQuery = {
    extend: function(sub, sup) {
      var val, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = sup.length; _i < _len; _i++) {
        val = sup[_i];
        if (sup.hasOwnProperty(val)) {
          _results.push(sub[val] = sup[val]);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

  Math.guid = function() {
    return ('xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      var r, v;
      r = Math.random() * 16 | 0;
      v = c === 'x' ? r : r & 0x3 | 0x8;
      return v.toString(16);
    })).toUpperCase();
  };

  Model = {
    inherited: function() {
      return console.log("inherited");
    },
    created: function() {
      return console.log("created");
    },
    prototype: {
      init: function() {
        return console.log("init");
      }
    },
    create: function() {
      var obj;
      obj = Object.create(this);
      obj.parent = this;
      console.log(obj.parent === obj.__proto__);
      obj.prototype = Object.create(this.prototype);
      obj.created();
      this.inherited(obj);
      return obj;
    },
    init: function() {
      var instance;
      instance = Object.create(this.prototype);
      instance.parent = this;
      instance.init.apply(instance, arguments);
      return instance;
    },
    extend: function(o) {
      var extended;
      extended = o.extended;
      jQuery.extend(this, o);
      if (extended) {
        return extended(this);
      }
    },
    include: function(o) {
      var included;
      included = o.included;
      jQuery.extend(this.prototype, o);
      if (included) {
        return included(this);
      }
    }
  };

  User = Model.create();

  User.init();

}).call(this);
