// Generated by CoffeeScript 1.6.3
(function() {
  var Pubsub;

  Pubsub = {
    subscribe: function(ev, callback) {
      var calls, _base;
      calls = this._callback || (this._callback = {});
      ((_base = this._callback)[ev] || (_base[ev] = [])).push(callback);
      return this;
    },
    publish: function() {
      var args, ev, item, list, _i, _len;
      args = Array.prototype.slice.call(arguments, 0);
      ev = args.shift();
      if (!this._callback) {
        return this;
      }
      if (!this._callback[ev]) {
        return this;
      }
      list = this._callback[ev];
      for (_i = 0, _len = list.length; _i < _len; _i++) {
        item = list[_i];
        item.apply(this, arguments);
      }
      return this;
    }
  };

  Pubsub.subscribe("wem", function() {
    return console.log("Wem!");
  });

  Pubsub.publish("wem");

}).call(this);
