// Generated by CoffeeScript 1.6.3
(function() {
  var mp3info, mpg123n, player;

  mpg123n = require('mpg123n');

  mp3info = require('mp3info');

  player = new mpg123n.Player;

  mp3info('/home/paul/mvcproject/betty.mp3', function(err, data) {
    if (err) {
      console.log(err);
    }
    return console.log(data);
  });

  player.play('/home/paul/mvcproject/betty.mp3');

  setTimeout((function() {
    return player.pause();
  }), 5000);

  setTimeout((function() {
    return player.pause();
  }), 12000);

}).call(this);
