// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    return {
      addHandler: function(el, type, handler, isBubbled) {
        if (el.addEventListener) {
          return el.addEventListener(type, handler, isBubbled);
        } else if (el.attachEvent) {
          return el.attachEvent('on' + type, handler);
        } else {
          return el['on' + type] = handler;
        }
      },
      removeHandler: function(el, type, handler) {
        if (el.removeEventListener) {
          return el.removeEventListener(type, handler, isBubbled);
        } else if (el.detachEvent('on' + type, handler)) {
          return el.detachEvent('on' + type, handler);
        } else {
          return el['on' + type] = null;
        }
      },
      getEvent: function(event) {
        if (event) {
          return event;
        } else {
          return window.event;
        }
      },
      getTarget: function(event) {
        return event.target || event.srcElement;
      },
      preventDefault: function(event) {
        if (event.preventDefault) {
          return event.preventDefault();
        } else {
          return event.returnValue = false;
        }
      },
      stopPropagation: function(event) {
        if (event.stopPropagation) {
          return event.stopPropagation();
        } else {
          return event.cancelBubble = false;
        }
      }
    };
  });

}).call(this);
