// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    var _hasFFPlugin, _hasIEPlugin;
    _hasFFPlugin = function(name) {
      var item, _i, _len, _ref;
      this.name = name;
      _ref = navigator.plugins;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        if (item.name.toLowerCase().indexOf(name) > -1) {
          return true;
        }
      }
      return false;
    };
    _hasIEPlugin = function(name) {
      var e;
      try {
        new ActiveXObject(name);
        return true;
      } catch (_error) {
        e = _error;
        return false;
      }
    };
    return {
      hasFlash: function(name) {
        var result;
        result = _hasFFPlugin('Flash');
        if (!result) {
          result = _hasIEPlugin("ShockwaveFlash.ShockwaveFlash");
        }
        return result;
      }
    };
  });

}).call(this);
