// Generated by CoffeeScript 1.6.3
(function() {
  var city, forecast, futurists, name, street, temp, theBait, theSwitch, weatherReport, _ref, _ref1, _ref2, _ref3;

  theBait = 1000;

  theSwitch = 0;

  _ref = [theSwitch, theBait], theBait = _ref[0], theSwitch = _ref[1];

  weatherReport = function(location) {
    return [location, 72, "Mostly Sun"];
  };

  _ref1 = weatherReport("Berkeley, CA"), city = _ref1[0], temp = _ref1[1], forecast = _ref1[2];

  futurists = {
    sculptor: "Umberto Boccioni",
    painter: "Vladimir Buriliuk",
    poet: {
      name: "Ft",
      address: ["Via", "Bellagio"]
    }
  };

  _ref2 = futurists.poet, name = _ref2.name, (_ref3 = _ref2.address, street = _ref3[0], city = _ref3[1]);

}).call(this);
