// Generated by CoffeeScript 1.6.3
(function() {
  var close, contents, open, other, tag, _i, _ref,
    __slice = [].slice;

  tag = "<impossible>";

  _ref = tag.split(""), open = _ref[0], contents = 4 <= _ref.length ? __slice.call(_ref, 1, _i = _ref.length - 2) : (_i = 1, []), close = _ref[_i++], other = _ref[_i++];

}).call(this);
