// Generated by CoffeeScript 1.6.3
(function() {
  var Account,
    _this = this;

  Account = function(customer, cart) {
    this.customer = customer;
    return this.cart = cart;
  };

  $(".shopping_cart").bind('click', function(event) {
    return _this.customer.purchase(_this.cart);
  });

}).call(this);
