// Generated by CoffeeScript 1.6.3
(function() {
  var filename, _fn, _i, _j, _len, _len1;

  _fn = function(filename) {
    return fs.readFile(filename, function(err, contents) {
      return compile(filename, contents.toString());
    });
  };
  for (_i = 0, _len = list.length; _i < _len; _i++) {
    filename = list[_i];
    _fn(filename);
  }

  /*
  --->
  */


  for (_j = 0, _len1 = list.length; _j < _len1; _j++) {
    filename = list[_j];
    (function(filename) {
      return fs.readFile(filename, function(err, contents) {
        return compile(filename, contents.toString());
      });
    });
  }

}).call(this);
