// Generated by CoffeeScript 1.6.3
(function() {
  var changeNumbers, inner, outer;

  console.log(['ff', 'dd', 'ee', 'tt'].slice(2).join(','));

  outer = 1;

  inner = 2;

  changeNumbers = function() {
    inner = -1;
    return outer = 10;
  };

  inner = changeNumbers();

}).call(this);
