// Generated by CoffeeScript 1.6.3
(function() {
  var cholesterol, healthy, html, numbers, _ref;

  cholesterol = 127;

  healthy = (200 > cholesterol && cholesterol > 60);

  html = "<strong>\n	cup of coffeescript\n</strong>";

  /*
  SkinnyMocha
  */


  numbers = ['0', '1', '2', '4'];

  [].splice.apply(numbers, [0, 3].concat(_ref = ['7', '8', '9'])), _ref;

  (html || (html = {}))[id];

}).call(this);
