// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = (function() {
    var WorkerBox, addToBoxList, addToBoxMap, boxList, boxMap, crypto, dispatch, emitter, next, removeBox;
    WorkerBox = require('./workerbox');
    crypto = require('crypto');
    emitter = new (require('events').EventEmitter)();
    boxList = [];
    boxMap = {};
    addToBoxMap = function(conn, socket) {
      var box;
      box = new WorkerBox(conn, socket);
      boxMap[conn.id] = box;
      return console.log('add new connection ' + conn.id + ' list index:' + box.index);
    };
    addToBoxList = function(box) {
      box.index = boxList.push(box) - 1;
      return console.log('add worker list index is ' + box.index);
    };
    dispatch = function(job) {
      var target;
      target = crypto.pseudoRandomBytes(32)[1] % boxList.length;
      return boxList[target].add(job);
    };
    removeBox = function(conn) {
      var box;
      box = boxMap[conn.id];
      if (box) {
        console.log('remove connection ' + conn.id);
        if (box.index) {
          boxList.splice(boxMap[conn.id].index, 1);
        }
        boxMap[conn.id].unBox();
        boxMap[conn.id] = null;
        return delete boxMap[conn.id];
      }
    };
    next = function(index) {
      return boxList[(index + 1) % boxList.length];
    };
    emitter.on('dispatch', dispatch);
    return {
      next: next,
      addToBoxMap: addToBoxMap,
      addToBoxList: addToBoxList,
      dispatch: dispatch,
      removeBox: removeBox,
      on: emitter.on.bind(emitter),
      off: emitter.removeListener.bind(emitter),
      emit: emitter.emit.bind(emitter)
    };
  })();

}).call(this);
