// Generated by CoffeeScript 1.6.3
(function() {
  var client, inbox, options;

  inbox = require('inbox');

  options = {
    secureConnection: true,
    auth: {
      user: 'paul.wu@radicasys.com',
      pass: 'HAha12345'
    }
  };

  client = inbox.createConnection(993, 'outlook.office365.com', options);

client.on('connect', function() {
   client.openMailbox("INBOX", function(error, info){
            if(error) throw error;
             client.on('new', function() {
              return console.log('new message');
            });
            client.listMessages(-5, function(err, messages){
                messages.forEach(function(message){
                    console.log(message.UID + ": " + message.title);
                    client.fetchData(message.UID , function(error , message){
                        console.log(message.flags);
                        console.log(message);
                    });
                    client.createMessageStream(message.UID).pipe(process.stdout, {end: false});
                });
            });

        });
  });

 

  client.connect();

}).call(this);
