// Generated by CoffeeScript 1.6.3
(function() {
  var fs, path, _buildAmdMod, _wrapAmd;

  fs = require('fs');

  path = require('path');

  _buildAmdMod = function(path) {
    var content;
    content = fs.readFileSync(path, {
      encoding: 'utf-8'
    });
    content = _wrapAmd({
      'path': path,
      'content': content.replace(/(\'|\")/g, '\\\'')
    });
    return fs.writeFileSync(path + '.js', content, {
      encoding: 'utf-8'
    });
  };

  _wrapAmd = function(tpl) {
    return "define ([\'" + tpl.path + "\'] , function(require) {\n var EJS = require('ace-ejs');\n return {\n tpl : new EJS({'text': \'" + tpl.content + "\'})};\n});";
  };

  _buildAmdMod('./test/ejs/test.ejs');

}).call(this);
